// Vocabulary data ported from shirin_baghdad_v2.html
export const VOCAB = [
  {g:'Verbs — from the transcript'},
  {ar:'بَعَثَ',en:'sent / dispatched',t:'v'},
  {ar:'يَبْعَثُ',en:'sends / dispatches (present)',t:'v'},
  {ar:'عَرَفَ',en:'recognised / knew',t:'v'},
  {ar:'يَعْرِفُ',en:'knows / recognises (present)',t:'v'},
  {ar:'يَسْكُنُ',en:'lives / resides',t:'v'},
  {ar:'يَعْمَلُ',en:'works',t:'v'},
  {ar:'نَسِيَ',en:'forgot',t:'v'},
  {ar:'اكْتَشَفَ',en:'discovered / found out',t:'v'},
  {ar:'يَضْحَكُ',en:'laughs',t:'v'},
  {ar:'يَلْحَقُ',en:'follows / catches up with',t:'v'},
  {ar:'يَنْظُرُ',en:'looks / gazes',t:'v'},
  {ar:'شَبِعَ',en:'became full (after eating)',t:'v'},
  {ar:'يَصْنَعُ',en:'makes / prepares',t:'v'},
  {ar:'يَحُثُّ',en:'urges / encourages',t:'v'},
  {ar:'نَسْتَقْبِلُ',en:'we receive / we welcome',t:'v'},
  {ar:'تَوَقَّفَ',en:'stopped',t:'v'},
  {ar:'تَصِلُ',en:'reaches / arrives',t:'v'},
  {g:'Nouns — from the transcript'},
  {ar:'رِسَالَة',en:'letter / message',t:'n'},
  {ar:'بَاب',en:'door',t:'n'},
  {ar:'حَي',en:'neighbourhood / district',t:'n'},
  {ar:'خَط',en:'handwriting / line',t:'n'},
  {ar:'طَيَران',en:'aviation / flying',t:'n'},
  {ar:'مُسْتَشْفَى',en:'hospital',t:'n'},
  {ar:'نَجَّار',en:'carpenter',t:'n'},
  {ar:'شُرْطِيّ',en:'policeman',t:'n'},
  {ar:'مُرُور',en:'traffic',t:'n'},
  {ar:'تَرْبِيَة',en:'upbringing / education',t:'n'},
  {ar:'عِنَايَة',en:'care / attention',t:'n'},
  {ar:'مَنْزِل',en:'house / home',t:'n'},
  {ar:'مُحَقِّق',en:'detective / investigator',t:'n'},
  {ar:'كِتَابَة',en:'writing',t:'n'},
  {ar:'ظَرْف',en:'envelope',t:'n'},
  {ar:'أَسْرَة',en:'family',t:'n'},
  {ar:'عَادَات',en:'habits / customs',t:'n'},
  {ar:'أَهْل',en:'family / people',t:'n'},
  {ar:'حَلْوَى',en:'sweets / dessert',t:'n'},
  {ar:'ضُيُوف',en:'guests',t:'n'},
  {ar:'غَدَاء',en:'lunch',t:'n'},
  {ar:'يَافِطَة',en:'sign / notice board',t:'n'},
  {ar:'لِسَان',en:'tongue / language',t:'n'},
  {ar:'خُلُق',en:'character / morals',t:'n'},
  {g:'Adjectives — from the transcript'},
  {ar:'جَيِّد',en:'good',t:'adj'},
  {ar:'لَذِيذ',en:'delicious / tasty',t:'adj'},
  {ar:'جَمِيل',en:'beautiful / nice',t:'adj'},
  {ar:'صَالِح',en:'righteous / good (person)',t:'adj'},
  {ar:'رَفِيع',en:'refined / elevated (of character)',t:'adj'},
  {ar:'جَائِع',en:'hungry',t:'adj'},
  {ar:'سَعِيد',en:'happy',t:'adj'},
  {ar:'مُكَرَّم',en:'honoured / respected',t:'adj'},
];

// flat vocab for testing (no group headers)
export const VOCAB_FLAT = VOCAB.filter(v => !v.g);
